id: springboot-configprops

info:
  name: Detect Springboot Configprops Actuator
  author: 信息泄漏
  severity: low
  description: Sensitive environment variables may not be masked
  tags: springboot,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/configprops"
      - "{{BaseURL}}/actuator/configprops"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "org.springframework.boot.actuate"
          - "beans"
          - "contexts"
        condition: and
      - type: status
        status:
          - 200
      - type: word
        words:
          - "application/json"
          - "application/vnd.spring-boot.actuator"
          - "application/vnd.spring-boot.actuator.v1+json"
        condition: or
        part: header
