id: misconfigured-concrete5

info:
  name: Misconfigured Concrete5
  author: 配置风险
  severity: low
  tags: misconfig,concrete,cms

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    host-redirects: true
    max-redirects: 2
    matchers:
      - type: word
        part: body
        words:
          - 'concrete5 has encountered an issue'