id: prometheus-log

info:
  name: Exposed Prometheus
  author: 配置风险
  severity: low
  tags: prometheus

requests:
  - method: GET
    path:
      - "{{BaseURL}}/prometheus"
      - "{{BaseURL}}/actuator/prometheus"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'gateway_request_total'
          - 'logback_events_total'
        condition: or

      - type: status
        status:
          - 200
