id: prometheus-exporter

info:
  name: Prometheus exporter detect
  author: 配置风险
  severity: info
  description: Prometheus exporter detector
  reference:
    - https://github.com/prometheus/prometheus/wiki/Default-port-allocations
  tags: prometheus

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'Exporter'
          - '<a href="/metrics">Metrics</a>'
        condition: and

    extractors:
      - type: regex
        part: body
        group: 1
        regex:
          - "<title>(.*?)</title>"