id: wamp-server-configuration

info:
  name: default-wamp-server-page
  author: 配置风险
  severity: medium
  description: Wamp default page will expose sensitive configuration and vhosts.
  reference: https://www.exploit-db.com/ghdb/6891.
  tags: wamp,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:
      - type: dsl
        dsl:
          - 'contains(tolower(body), "wampserver")'

      - type: status
        status:
          - 200
